// Scans public/media for real files (ignoring .gitkeep) and writes a manifest
// the app uses to highlight nodes that actually have media.
// Runs automatically before `npm run dev` and `npm run build` (see package.json).
import { EXAMPLES } from '../src/data/portfolio.js'
import { readdirSync, existsSync, writeFileSync } from 'fs'
import { join } from 'path'

const SUBS = { Videos: 'videos', Photos: 'photos', Gifs: 'gifs', Models: 'models' }

function countFiles(dir) {
  if (!existsSync(dir)) return 0
  return readdirSync(dir).filter((f) => f !== '.gitkeep' && !f.startsWith('.')).length
}

const manifest = {}
for (const e of EXAMPLES) {
  const base = join('public', 'media', ...e.folder.split('/'))
  const entry = {}
  let total = 0
  for (const [sub, key] of Object.entries(SUBS)) {
    const c = countFiles(join(base, sub))
    if (c) { entry[key] = c; total += c }
  }
  entry.hasFiles = total > 0
  manifest[e.id] = entry
}

const out =
  `// AUTO-GENERATED by scripts/scan-media.mjs — do not edit by hand.\n` +
  `// Regenerated on every \`npm run dev\` / \`npm run build\`.\n` +
  `export const MEDIA_MANIFEST = ${JSON.stringify(manifest, null, 2)}\n`

writeFileSync(join('src', 'data', 'mediaManifest.js'), out)

const filled = Object.entries(manifest).filter(([, v]) => v.hasFiles).map(([k]) => k)
console.log(`Wrote src/data/mediaManifest.js`)
console.log(`Nodes with media (${filled.length}): ${filled.join(', ') || 'none'}`)
