// Scans public/media for real files (ignoring .gitkeep) and writes a manifest
// the app uses to (a) highlight projects that have media and (b) prefetch.
// Runs automatically before `npm run dev` and `npm run build` (see package.json).
import { EXAMPLES } from '../src/data/portfolio.js'
import { readdirSync, existsSync, writeFileSync } from 'fs'
import { join } from 'path'

const SUBS = { Videos: 'videos', Photos: 'photos', Gifs: 'gifs', Models: 'models' }

const manifest = {}
const files = []   // flat list of every media URL, used by the "preload all" button

for (const e of EXAMPLES) {
  const base = join('public', 'media', ...e.folder.split('/'))
  const entry = {}
  let total = 0
  for (const [sub, key] of Object.entries(SUBS)) {
    const dir = join(base, sub)
    if (!existsSync(dir)) continue
    const names = readdirSync(dir)
      .filter((f) => f !== '.gitkeep' && !f.startsWith('.'))
      .sort()
    if (names.length) { entry[key] = names.length; total += names.length }
    for (const n of names) files.push(`./media/${e.folder}/${sub}/${n}`)
  }
  entry.hasFiles = total > 0
  manifest[e.id] = entry
}

const out =
  `// AUTO-GENERATED by scripts/scan-media.mjs — do not edit by hand.\n` +
  `// Regenerated on every \`npm run dev\` / \`npm run build\`.\n` +
  `export const MEDIA_MANIFEST = ${JSON.stringify(manifest, null, 2)}\n\n` +
  `export const MEDIA_FILES = ${JSON.stringify(files, null, 2)}\n`

writeFileSync(join('src', 'data', 'mediaManifest.js'), out)

const filled = Object.entries(manifest).filter(([, v]) => v.hasFiles).map(([k]) => k)
console.log(`Wrote src/data/mediaManifest.js`)
console.log(`Nodes with media (${filled.length}): ${filled.join(', ') || 'none'}`)
console.log(`Total media files for prefetch: ${files.length}`)
